### ISSUE TITLE
Not losing elo when taking the first place

### ISSUE THREAD

**Issue by coozieki** [kiwec/osu-ranked-lobbies#22] opened 2021-12-19 21:29 UTC
![image](https://user-images.githubusercontent.com/69788536/146691372-86b1d9cb-da9d-460c-88cd-f611bc302865.png)

That's just weird. Can just check if a player placed first and don't let him get negative elo. Set it to at least 0 or maybe +1 idk.

**Comment by kiwec** [comment] 2021-12-20 15:55
The fix would be to remove first/second/etc place players that would lose elo by "winning" from the match. As in, act like they're not even in the lobby for that match.

It's easy to add, but first I need to fix lobby desync and re-enable anti-dodging or else players will start farming low-level lobbies again.

**Comment by coozieki** [comment] 2021-12-23 20:43
![image](https://user-images.githubusercontent.com/69788536/147289912-7d3036e8-39b0-46b2-8471-173eceb2a2fb.png)

Apparently the history is just displayed wrong

**Comment by kiwec** [comment] 2021-12-25 08:51
> Apparently the history is just displayed wrong

No, the history is a bit confusing because the elo displayed on the user profile includes rank decay and variance debuffs, while the elo changes don't (and can't, because rank decay gets reset to 0 after you set a score). So you *can* gain ranks while losing elo, but you still lost elo while getting first place, which isn't desirable.

**Comment by kiwec** [comment] 2022-01-02 09:23
Fixed in https://github.com/kiwec/osu-ranked-lobbies/commit/4c8b60dc2802b27d79b19aac7aa9d76c2e10b14c

NOTE: This only applied in ~20 scores (out of 500k+). It turns out that most cases were caused by invalid score display.

**Closed by kiwec** 2022-01-02 09:23 UTC
Labels: invalid
